### ISSUE TITLE
Cannot read property lang of null

### ISSUE THREAD

**Issue by MichaelS717** [AndrewLaneX/AntiUserbotBot#6]
I am trying to host this bot myself but I get this:

```
PS D:\AntiUserbotBot> npm start

> antiuserbotbot@1.0.0 start D:\AntiUserbotBot
> node index.js

@antiuserrobot is running...
D:\AntiUserbotBot\middleware\i18n.js:21
                    resolve(i18n(chat.lang, keyword, variables));
                                      ^

TypeError: Cannot read property 'lang' of null
    at D:\AntiUserbotBot\middleware\i18n.js:21:39
    at newArguments.<computed> (D:\AntiUserbotBot\node_modules\nedb\lib\executor.js:29:17)
    at Cursor.execFn (D:\AntiUserbotBot\node_modules\nedb\lib\datastore.js:520:14)
    at callback (D:\AntiUserbotBot\node_modules\nedb\lib\cursor.js:126:19)
    at D:\AntiUserbotBot\node_modules\nedb\lib\cursor.js:193:12
    at D:\AntiUserbotBot\node_modules\nedb\lib\datastore.js:329:14
    at Object.async.eachSeries (D:\AntiUserbotBot\node_modules\async\lib\async.js:130:20)
    at D:\AntiUserbotBot\node_modules\nedb\lib\datastore.js:323:11
    at fn (D:\AntiUserbotBot\node_modules\async\lib\async.js:582:34)
    at Immediate.<anonymous> (D:\AntiUserbotBot\node_modules\async\lib\async.js:498:34)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! antiuserbotbot@1.0.0 start: `node index.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the antiuserbotbot@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

**Comment by AndrewLaneX** [comment]
Thanks for the report!
